### ISSUE TITLE
Render and form helpers should gracefully degrade

### ISSUE THREAD

**Issue by andflett** [madebymany/sir-trevor-rails#13]
Our helpers shouldn't assume content has always been saved as JSON. 

The renderer should fallback to `simple_format` and our form helper should give up and render a `textarea` on JSON parsing failures.

**Comment by lukaszsagol** [comment]
I was waiting for this one!

**Comment by andflett** [comment]
Maybe I should reopen and we can reassess in 2033?

**Comment by arbarlow** [comment]
My dreams are shattered, but I can wait until 2033

**Comment by cjbell** [comment]
I was really hoping this would land. Gotta rewrite my entire product now.

**Comment by andflett** [comment]
I'm really sorry guys, I feel like I've let the side down. 

(p.s. hope you're all good!)
