### ISSUE TITLE
Rails 4.2.1 issue

### ISSUE THREAD

**Issue by SergeyKishenin** [madebymany/sir-trevor-rails#38]
With Rails 4.2.1 I get

```
You have the following errors:
There was a problem loading the contents of the document
```

In JS console:

`Sorry there has been a problem with parsing the JSON`
`SyntaxError: Unexpected token #`

while with Rails 4.2.0 it works fine.

**Comment by cbeer** [comment]
We ran into the same problem with Rails 4.2.1. It looks like, under Rails 4.2.1:

```
<%= f.text_area :content %>
```

is no longer providing the string value of content, but we're getting the Ruby serialization instead:

```
[#&lt;SirTrevorRails::Blocks::TextBlock text=&quot;&lt;p&gt;text&lt;/p&gt;&quot;, isHtml=true&gt;]
```

A workaround seems to be doing something like:

```
<%= f.text_area :content, value: f.object['content'] %>
```

**Comment by ninjabiscuit** [comment]
Thanks for reporting. I’ll look into what we can do about getting this fixed


-- 
Andrew Walker ["@ninjabiscuit", "07886655448"]
http://madebymany.com

On 24 March 2015 at 16:28:53, Chris Beer (notifications@github.com) wrote:

We ran into the same problem with Rails 4.2.1. It looks like, under Rails 4.2.1:

<%= f.text_area :content %>

is no longer providing the string value of content, but we're getting the Ruby serialization instead:

[#&lt;SirTrevorRails::Blocks::TextBlock text=&quot;&lt;p&gt;text&lt;/p&gt;&quot;, isHtml=true&gt;]

A workaround seems to be doing something like:

<%= f.text_area :content, value: f.object['content'] %>

**Comment by adamcarlile** [comment]
I've managed to fix this in my application by writing an initialiser to add a to_s method that constructs a JSON object for the block array.

```ruby
module SirTrevorRails
  class BlockArray < Array
    def to_s
      {data: as_json}.to_json
    end
  end
end
```

**Comment by zaparka** [comment]
I have same issue with rails 4.2.3

**Comment by milushov** [comment]
same issue, my workaround is `f.object.read_attribute(:content)`

**Comment by ninjabiscuit** [comment]
This should be fixed now. We also have Travis running against a few different versions of ruby so things like this should get caught a little easier from now on

**Comment by adamcarlile** [comment]
Thanks @ninjabiscuit

**Comment by ninjabiscuit** [comment]
@adamcarlile np :+1:
